# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160822_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.ImageField(default='default/project.png', upload_to='p_img_preview'),
        ),
    ]
