# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(default='project_none', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
