# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160825_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default/project.png', upload_to='avatar'),
        ),
    ]
