# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160828_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='nomail@no.no', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='send_email_messages',
            field=models.BooleanField(default=True),
        ),
    ]
